import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../data/providers/data_providers.dart';
import '../../../routes/app_router.dart';
import '../../../models/service_request_model.dart';
import 'controllers/create_request_controller.dart';

class CustomerCreateRequestScreen extends ConsumerStatefulWidget {
  const CustomerCreateRequestScreen({super.key, required this.equipmentId});
  final int equipmentId;

  @override
  ConsumerState<CustomerCreateRequestScreen> createState() => _CustomerCreateRequestScreenState();
}

class _CustomerCreateRequestScreenState extends ConsumerState<CustomerCreateRequestScreen> {
  final _formKey = GlobalKey<FormState>();
  final _descController = TextEditingController();

  @override
  void dispose() {
    _descController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final equipmentFuture = ref.watch(equipmentRepositoryProvider).getEquipmentById(widget.equipmentId);
    final state = ref.watch(createRequestControllerProvider);

    return Scaffold(
      appBar: AppBar(title: const Text('Create Damage Report')),
      body: FutureBuilder(
        future: equipmentFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) return const Center(child: CircularProgressIndicator());
          final equipment = snapshot.data;
          if (equipment == null) return const Center(child: Text('Equipment not found.'));

          return SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('${equipment.brand} - ${equipment.typeModel}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                          Text('SN: ${equipment.serialNumber}'),
                          Text('Location: ${equipment.location}'),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                  TextFormField(
                    controller: _descController,
                    decoration: const InputDecoration(
                      labelText: 'Problem Description',
                      hintText: 'Describe the issue...',
                      border: OutlineInputBorder(),
                    ),
                    maxLines: 4,
                    validator: (v) {
                      if (v == null || v.trim().isEmpty) return 'Description is required';
                      if (v.trim().length < 10) return 'Please provide more details (min 10 chars)';
                      return null;
                    },
                  ),
                  const SizedBox(height: 32),
                  ElevatedButton(
                    onPressed: state.isLoading ? null : () async {
                      if (_formKey.currentState!.validate()) {
                        final req = ServiceRequestModel(
                          id: 0, // generated by repo
                          ticketNumber: '', // generated by repo
                          customerId: equipment.customerId, // available
                          equipmentId: equipment.id,
                          problemDescription: _descController.text.trim(),
                          status: 'Pending',
                          createdAt: DateTime.now(),
                          customerName: equipment.customerName,
                          equipmentBrand: equipment.brand,
                          equipmentModel: equipment.typeModel,
                        );
                        
                        final success = await ref.read(createRequestControllerProvider.notifier).createRequest(req);
                        if (!context.mounted) return;
                        if (success) {
                          context.goNamed(AppRoutes.customerDashboard);
                        }
                      }
                    },
                    child: state.isLoading ? const CircularProgressIndicator() : const Text('Submit Report'),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
